kumuluzee:
  name: sporocilniSistem
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://192.168.99.100:8081
    http:
      port: 8081

  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
      - name: orders-endpoint
        url-pattern: /v1/sporocilniSistem/*
rest-properties:
  healthy: true