apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sporocilniSistem-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sporocilniSistem-profilov
    spec:
      containers:
      - image: tjasaj/sporocilniSistem-profilov:0.01
        name: sporocilniSistem-profilov
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP