apiVersion: v1
kind: Service
metadata:
  name: sporocilniSistem-service
  labels:
    app: sporocilniSistem-profilov
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: sporocilniSistem-profilov