apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sporocilni-sistem-service-monitor
  labels:
    team: katalogteam
spec:
  selector:
    matchLabels:
      app: sporocilni-sistem
  endpoints:
  - port: server