apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sporocilniSistem-service-monitor
  labels:
    team: katalogteam
spec:
  selector:
    matchLabels:
      app: sporocilniSistem-profilov
  endpoints:
  - port: server