apiVersion: v1
kind: Service
metadata:
  name: sporocilni-sistem-service
  labels:
    app: sporocilni-sistem
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30133
  selector:
    app: sporocilni-sistem